# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QMessageBox
import demo_base


class Ui_MainWindow(object):
    video_path = None
    result_path = None
    vol_thresh = 60

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 430)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(330, 170, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(330, 220, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 100, 72, 15))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(220, 100, 381, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(260, 360, 72, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(320, 360, 113, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(MainWindow.selectfile) # type: ignore
        self.pushButton_2.clicked.connect(MainWindow.detectobject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "选择文件"))
        self.pushButton_2.setText(_translate("MainWindow", "开始追踪"))
        self.label.setText(_translate("MainWindow", "视频位置"))
        self.label_2.setText(_translate("MainWindow", "车辆限速"))

    def selectfile(self):
        filename, filetype = QFileDialog.getOpenFileName(self, "选择视频", '', '(*.mp4)')
        if filename:
            self.lineEdit.setText(filename)
            self.video_path = filename
            pos = 0
            print(filename)
            for i in range(len(filename) - 1, 0, -1):
                if filename[i] == '.':
                    pos = i
                    break
            self.result_path = filename[0:pos]
            self.result_path += "_result.mp4"

    def detectobject(self):
        # print(self.video_path)
        if self.video_path is None:
            QMessageBox.critical(self, "error", "您未选择文件!")
            return
        vol = self.lineEdit_2.text()
        if  len(vol) != 0:
            if vol.isdigit():
                self.vol_thresh = int(vol)
            else:
                QMessageBox.critical(self, '输入错误', '输入速度应当为数字!', QMessageBox.Ok)
                self.lineEdit_2.setText("")
                return 
        obj_number, sec = demo_base.detect(self.video_path, self.result_path, self.vol_thresh)
        text = "{:.2f}秒内，总计出现{}个目标".format(sec, obj_number)
        text += "\n文件存放于" + self.result_path
        QMessageBox.information(self, '统计结果', text, QMessageBox.Ok)
        self.result_path = self.video_path = None
        self.lineEdit.setText("")
